### ISSUE TITLE
License

### ISSUE THREAD

**Issue by shobute** [sghall/d3-chord-diagrams#1]
I would like to use mapper.js in my code but I see no license listed. Is it public domain?

**Comment by peterjmag** [comment]
+1! I'd also like to use mapper.js in a project I'm working on.

**Comment by sghall** [comment]
When you're right, you're right.  Thanks for pointing out that there was not a license on here.  I just added it (MIT).  Please feel free to do whatever you need with the code.

**Comment by peterjmag** [comment]
Great, thanks @sghall!
